before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    id: github.com/joshuar/go-gadget-go
    package_name: go-gadget-go
    vendor: github.com/joshuar
    homepage: https://github.com/joshuar/cf-ddns
    maintainer: Josh Rich <joshua.rich@gmail.com>
    description: A Dynamic DNS client for Cloudflare.
    license: MIT
    release: 1
    formats:
      - deb
      - rpm
    section: default
    priority: extra
    dependencies:
      - ansible
    contents:
      - src: assets/ansible/facts.d/nmcli.fact
        dst: /etc/ansible/facts.d/nmcli.fact
      - src: assets/ansible/facts.d/tuned.fact
        dst: /etc/ansible/facts.d/tuned.fact
