before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    id: github.com/joshuar/go-gadget-go
    package_name: go-gadget-go
    vendor: github.com/joshuar
    homepage: https://github.com/joshuar/go-gadget-go
    maintainer: Josh Rich <joshua.rich@gmail.com>
    description: Generate extra facts for Ansible from command-line tools
    license: MIT
    release: 1
    formats:
      - deb
      - rpm
    replacements:
      amd64: x86_64
      386: i386
    section: default
    priority: extra
    recommends:
      - ansible
    bindir: /usr/bin
    contents:
      - src: assets/usr/bin/go-gadget-go.sh
        dst: /usr/bin/go-gadget-go.sh
      - src: /usr/bin/go-gadget-go.sh
        dst: /etc/ansible/facts.d/nmcli.fact
        type: "symlink"
      - src: /usr/bin/go-gadget-go.sh
        dst: /etc/ansible/facts.d/tuned.fact
        type: "symlink"
      - src: /usr/bin/go-gadget-go.sh
        dst: /etc/ansible/facts.d/firewalld.fact
        type: "symlink"
      - src: LICENSE
        dst: /usr/share/go-gadget-go/LICENSE
      - src: README.md
        dst: /usr/share/go-gadget-go/README.md